0.2: run trid locally to grab the downloaded version

diff --git a/trid-package b/trid-package
--- a/trid-package
+++ b/trid-package
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Define script version
-VERSION=0.1
+VERSION=0.2
 
 CURDIR="$(pwd)"
 
@@ -45,10 +45,20 @@ cd "$TEMPDIR/trid-autobuilt"
 echo "Extracting trid binary package."
 unzip ../trid_linux.zip -d .
 chmod +x ./trid
+
+TRID_VERSION="$(LANG=C trid -? 2>&1 | grep -Eo 'v[0-9]+\.[0-9]+' | cut -c 2-)"
+retval=$?
+if [ $retval -eq 1 ]; then
+    echo "Failed to obtain trid version."
+	exit $retval
+fi
+
+echo "Got $TRID_VERSION as trid version"
+
 echo "Extracting trid definitions package."
 unzip ../triddefs.zip -d .
 
-DEBVERSIONSTRING="0~$(date "+%Y%m%d")+tp$VERSION"
+DEBVERSIONSTRING="${TRID_VERSION}~$(date "+%Y%m%d")+auto$VERSION"
 echo "Preparing Debian package in $TEMPDIR/trid-autobuilt/ (version: $DEBVERSIONSTRING)"
 cp -R "$SCRIPT_DIR/debian-autogen/" "./debian"
 dch --create --package "trid-autobuilt" --newversion "$DEBVERSIONSTRING" "Automatically generated by trid-package $VERSION."
